"""How many contexts fit?  Capacity vs embedding dimension, trained vs Hebbian.

d = 256 next tokens, h in {32 ... 2048}, 3 seeds, and for every (model, h, seed) a
bisection on the number of contexts n, narrowed to `--precision` (default 8), for the
largest n whose *every* context is retrieved correctly.

The trained model is Adam on the full-batch cross-entropy, run **to saturation**: a
candidate n is only declared out of reach once the accuracy has stopped improving, never
because a step budget ran out.

Writes
    results/capacity.json        every probe, resumable -- re-running skips done cells
    results/capacity_chart.md    colloquium ```chart blocks, paste into slides.md

Usage
    PYTHONPATH=src uv run python scripts/capacity_sweep.py                 # everything
    PYTHONPATH=src uv run python scripts/capacity_sweep.py --h 128 256     # a slice
    PYTHONPATH=src uv run python scripts/capacity_sweep.py --chart-only    # redraw
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from assocmem.capacity import D_TOK, TrainConfig, capacity  # noqa: E402

HS = (32, 64, 128, 256, 512, 1024, 2048)
SEEDS = (0, 1, 2)
MODELS = ("hebbian", "trained")
OUT = pathlib.Path("results/capacity.json")
CHART = pathlib.Path("results/capacity_chart.md")
SLIDES = pathlib.Path("slides.md")
MARK_BEGIN = "<!-- BEGIN capacity-chart (generated by scripts/capacity_sweep.py) -->"
MARK_END = "<!-- END capacity-chart -->"

# Rough priors on capacity/h, used only to seed the bisection bracket (it is grown by
# doubling until it really brackets, so being wrong costs a probe, not correctness).
PRIOR = {"hebbian": 5.0, "trained": 38.0}

STYLE = {
    "trained": ("Trained (Adam, cross-entropy)", "#0f3460"),
    "hebbian": ("Hebbian", "#c0392b"),
}
CHART_ORDER = ("trained", "hebbian")  # legend order, best curve first
PARAM_LABEL = "One memory per parameter"
PARAM_COLOR = "#9ca3af"

# colloquium's chart element forwards only label / data / color per dataset and its
# Chart.js bootstrap parses the config out of a JSON attribute, so neither the marker
# size nor the tick labels can be asked for in the YAML.  Everything JSON can express
# is patched onto the attribute at parse time (before the deferred bootstrap reads it);
# the tick labels need real functions, so those arrive through a plugin registered on
# DOMContentLoaded -- earlier than colloquium's own handler, which is what builds the
# charts, so the plugin is in place by the time they are constructed.
# The styling itself lives in assets/capacity-chart.js (kept out of slides.md,
# like the rest of the deck's JS), so the generated block is just the tag.
STYLE_SCRIPT = '<script src="assets/capacity-chart.js"></script>'


# --------------------------------------------------------------------------- #
# store
# --------------------------------------------------------------------------- #
def load() -> dict:
    if OUT.exists():
        return json.loads(OUT.read_text())
    return {"d": D_TOK, "hs": list(HS), "seeds": list(SEEDS), "cells": {}}


def save(state: dict) -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(state, indent=1))


def key(model: str, h: int, seed: int) -> str:
    return f"{model}/h{h}/s{seed}"


# --------------------------------------------------------------------------- #
# chart
# --------------------------------------------------------------------------- #
def series(state: dict, model: str, hs, reduce="mean"):
    """[(h, value)] over the h that have all their seeds done."""
    out = []
    for h in hs:
        vals = [state["cells"][key(model, h, s)]["capacity"]
                for s in state["seeds"] if key(model, h, s) in state["cells"]]
        if len(vals) == len(state["seeds"]):
            f = {"mean": np.mean, "min": np.min, "max": np.max}[reduce]
            out.append((h, float(f(vals))))
    return out


def _points(pts, digits=1):
    return "\n".join(f"        - {{x: {h}, y: {round(v, digits)}}}" for h, v in pts)


def _bounds(values, pad=1.45):
    """Axis range: the data, padded by a constant factor on a log scale."""
    return min(values) / pad, max(values) * pad


def _legend_html(state: dict, *, reference: bool) -> str:
    """Stand-in for the Chart.js legend: a short line with its marker sitting on top.

    Chart.js draws legend keys as filled boxes, which look nothing like the thin
    lines on the plot, so the built-in legend is switched off and this replaces it.
    """
    entries = [STYLE[m] for m in CHART_ORDER if series(state, m, state["hs"])]
    if reference:
        entries.append((PARAM_LABEL, PARAM_COLOR))
    items = []
    for label, color in entries:
        dashed = label == PARAM_LABEL
        glyph = [f'<svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true">',
                 f'<line x1="1" y1="5" x2="29" y2="5" stroke="{color}" '
                 f'stroke-width="{1.5 if dashed else 2.2}"'
                 f'{' stroke-dasharray="6 5"' if dashed else ""}/>']
        if not dashed:
            glyph.append(f'<circle cx="15" cy="5" r="2.8" fill="{color}"/>')
        glyph.append("</svg>")
        items.append("<span>" + "".join(glyph) + label + "</span>")
    # Layout lives in .cap-legend (assets/slides.css); only the per-series
    # colour and dash pattern, which come from the data, stay inline.
    return '<div class="cap-legend">' + "".join(items) + "</div>"


def _axis(name: str, label: str, scale_type: str, bounds=None) -> list[str]:
    """One axis of the chart options; bounds is set for the bare (slide) version,
    which also drops the gridlines so only the curves and the tick marks are left."""
    lines = [f"    {name}:", f"      type: {scale_type}",
             f'      title: {{display: true, text: "{label}"}}']
    if bounds is None:
        return lines
    lo, hi = bounds
    # drawOnChartArea kills the gridlines but keeps the axis line and its tick marks,
    # which is the only departure from Chart.js' defaults here.
    return lines + [f"      min: {lo:.0f}", f"      max: {hi:.0f}",
                    "      grid: {drawOnChartArea: false}",
                    "      ticks: {padding: 8}"]


def chart_block(state: dict, hs, *, per_dim: bool, reference: bool = False,
                title: str | None = None, x_params: bool = False,
                bare: bool = False) -> str:
    """One colloquium ```chart block.

    x_params puts the parameter count d·h on the x axis instead of h, which is what
    makes the slope-1 reference read directly as "one memory per parameter".
    bare drops the title, the grid and the built-in legend, and leaves the tick
    labels to STYLE_SCRIPT (powers of two on x, powers of ten on y).
    """
    x_of = (lambda h: state["d"] * h) if x_params else (lambda h: h)
    x_label = "number of parameters d·h" if x_params else "embedding dimension h"
    if per_dim:
        default_title = (f"Capacity per embedding dimension (d = {state['d']}) "
                         "— flat means capacity ∝ h")
        y_label = "contexts stored per dimension of h"
    else:
        default_title = f"Contexts stored at 100 % accuracy (d = {state['d']})"
        y_label = "capacity" if bare else "contexts stored at 100 % accuracy"
    title = default_title if title is None else title
    lines = ["```chart", "type: line"]
    if not bare:
        lines.append(f'title: "{title}"')
    lines += ["data:", "  datasets:"]
    ys = []
    for model in CHART_ORDER:
        pts = series(state, model, hs)
        if not pts:
            continue
        if per_dim:
            pts = [(h, v / h) for h, v in pts]
        ys += [v for _, v in pts]
        label, color = STYLE[model]
        lines += [f'    - label: "{label}"', f'      color: "{color}"',
                  "      data:", _points([(x_of(h), v) for h, v in pts],
                                         2 if per_dim else 1)]
    if reference:
        # slope exactly 1 on a log-log plot: the yardstick the two curves are read
        # against.  d*h is the parameter count of W, i.e. one memory per parameter.
        ref = [(h, state["d"] * h) for h in hs]
        ys += [v for _, v in ref]
        lines += [f'    - label: "{PARAM_LABEL}"', f'      color: "{PARAM_COLOR}"',
                  "      data:", _points([(x_of(h), v) for h, v in ref], 0)]
    lines.append("options:")
    if bare:
        lines += ["  plugins:", "    legend: {display: false}"]
    lines += ["  scales:"] + _axis("x", x_label, "logarithmic",
                                   _bounds([x_of(h) for h in hs]) if bare else None)
    lines += _axis("y", y_label, "linear" if per_dim else "logarithmic",
                   _bounds(ys) if bare else None)
    lines.append("```")
    return "\n".join(lines)


def slide_body(state: dict) -> str:
    """The legend, the chart and its styling patch, as they appear on the slide."""
    return "\n".join([
        _legend_html(state, reference=True),
        "",
        chart_block(state, state["hs"], per_dim=False, reference=True,
                    x_params=True, bare=True),
        "",
        STYLE_SCRIPT,
    ])


def write_slide(state: dict) -> bool:
    """Replace the marked block in slides.md.  Returns False if the markers are gone."""
    text = SLIDES.read_text()
    a, b = text.find(MARK_BEGIN), text.find(MARK_END)
    if a < 0 or b < 0:
        return False
    SLIDES.write_text(text[:a] + MARK_BEGIN + "\n\n" + slide_body(state) + "\n\n"
                      + text[b:])
    return True


def fit_slope(pts):
    """Power-law exponent of value vs h."""
    if len(pts) < 2:
        return None
    h = np.log(np.array([p[0] for p in pts], float))
    v = np.log(np.array([p[1] for p in pts], float))
    a, b = np.polyfit(h, v, 1)
    r2 = 1.0 - np.sum((v - (a * h + b)) ** 2) / np.sum((v - v.mean()) ** 2)
    return float(a), float(np.exp(b)), float(r2)


def write_chart(state: dict) -> None:
    hs = state["hs"]
    parts = [
        "<!-- generated by scripts/capacity_sweep.py -- do not edit by hand -->",
        f"# Storage capacity vs embedding dimension (d = {state['d']}, "
        f"{len(state['seeds'])} seeds, bisection to precision "
        f"{state.get('precision', 8)})",
        "",
        "Mean over seeds of the largest number of contexts stored at 100 % accuracy.",
        "Paste either block into `slides.md`.",
        "",
        "## capacity vs the parameter count d·h  (dashed = one memory per parameter)",
        "",
        slide_body(state),
        "",
        "## capacity / h vs h",
        "",
        chart_block(state, hs, per_dim=True),
        "",
        "## numbers",
        "",
        "| h | " + " | ".join(f"{STYLE[m][0]}" for m in MODELS) + " |",
        "|---|" + "---|" * len(MODELS),
    ]
    for h in hs:
        row = [str(h)]
        for m in MODELS:
            vals = [state["cells"][key(m, h, s)]["capacity"]
                    for s in state["seeds"] if key(m, h, s) in state["cells"]]
            row.append(f"{np.mean(vals):.0f} ({min(vals)}–{max(vals)})" if
                       len(vals) == len(state["seeds"]) else "—")
        parts.append("| " + " | ".join(row) + " |")
    parts.append("")
    for m in MODELS:
        pts = series(state, m, hs)
        f = fit_slope(pts)
        if f:
            parts.append(f"* {STYLE[m][0]}: capacity ≈ {f[1]:.2f} · h^{f[0]:.3f} "
                         f"(r² = {f[2]:.4f}) over all h")
        # The small-h points carry real curvature -- the trained ratio is still
        # climbing there -- so the asymptotic slope is the honest one to quote.
        top = fit_slope(pts[-3:])
        if top and len(pts) >= 3:
            parts.append(f"  * top three h only: capacity ≈ {top[1]:.2f} · "
                         f"h^{top[0]:.3f}, i.e. {pts[-1][1] / pts[-1][0]:.1f} "
                         f"contexts per dimension "
                         f"({pts[-1][1] / (state['d'] * pts[-1][0]):.3f} per parameter)")
    CHART.parent.mkdir(parents=True, exist_ok=True)
    CHART.write_text("\n".join(parts) + "\n")


# --------------------------------------------------------------------------- #
# main
# --------------------------------------------------------------------------- #
def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--h", type=int, nargs="*", default=list(HS))
    ap.add_argument("--seeds", type=int, nargs="*", default=list(SEEDS))
    ap.add_argument("--models", nargs="*", default=list(MODELS))
    ap.add_argument("--precision", type=int, default=8)
    ap.add_argument("--lrs", type=float, nargs="*", default=[3.0])
    ap.add_argument("--segment", type=int, default=500)
    ap.add_argument("--patience", type=int, default=8)
    ap.add_argument("--max-steps", type=int, default=8_000)
    ap.add_argument("--chart-only", action="store_true")
    ap.add_argument("--write-slide", action="store_true",
                    help="also refresh the marked chart block in slides.md")
    ap.add_argument("--tag", default="")
    args = ap.parse_args()

    global OUT, CHART
    if args.tag:
        OUT = OUT.with_name(f"capacity_{args.tag}.json")
        CHART = CHART.with_name(f"capacity_{args.tag}.md")

    state = load()
    if args.chart_only:
        write_chart(state)
        print(f"wrote {CHART}")
        if args.write_slide:
            print(f"{'wrote' if write_slide(state) else 'MARKERS MISSING in'} {SLIDES}")
        return

    cfg = TrainConfig(lrs=tuple(args.lrs), segment=args.segment,
                      patience=args.patience, max_steps=args.max_steps)
    state["precision"] = args.precision
    state["train_config"] = dict(lrs=list(cfg.lrs), segment=cfg.segment,
                                 patience=cfg.patience, max_steps=cfg.max_steps)

    t_all = time.time()
    for model in args.models:
        for h in args.h:
            # seed the bracket from the seeds of this h already done, else from the
            # smaller h already done, else from the prior.
            done = [state["cells"][key(model, hh, s)]["capacity"] / hh
                    for hh in args.h for s in args.seeds
                    if key(model, hh, s) in state["cells"]]
            ratio = float(np.mean(done)) if done else PRIOR[model]
            for seed in args.seeds:
                k = key(model, h, seed)
                if k in state["cells"]:
                    print(f"[skip] {k} = {state['cells'][k]['capacity']}", flush=True)
                    continue
                print(f"[run ] {model} h={h} seed={seed} "
                      f"(guess {ratio * h:.0f})", flush=True)
                t0 = time.time()
                res = capacity(model, h, seed, precision=args.precision,
                               guess=int(round(ratio * h)), cfg=cfg,
                               log=lambda s: print(s, flush=True))
                dt = time.time() - t0
                state["cells"][k] = dict(
                    model=model, h=h, seed=seed, capacity=res.capacity,
                    upper=res.upper, n_probes=res.n_probes,
                    n_capped=res.n_capped, seconds=round(dt, 1),
                    per_h=round(res.capacity / h, 3), trace=res.trace)
                save(state)
                write_chart(state)
                print(f"[done] {k} capacity={res.capacity} "
                      f"(< {res.upper}, {res.capacity / h:.2f}·h) "
                      f"{res.n_probes} probes"
                      f"{f', {res.n_capped} capped' if res.n_capped else ''}"
                      f", {dt / 60:.1f} min", flush=True)
                ratio = float(np.mean(
                    [state["cells"][key(model, hh, s)]["capacity"] / hh
                     for hh in args.h for s in args.seeds
                     if key(model, hh, s) in state["cells"]]))
    write_chart(state)
    if args.write_slide and not write_slide(state):
        print(f"WARNING: markers missing in {SLIDES}, slide not refreshed", flush=True)
    print(f"\nall done in {(time.time() - t_all) / 60:.1f} min -> {OUT}, {CHART}",
          flush=True)


if __name__ == "__main__":
    main()
