"""The three compute-optimal slides of Part I, read off one Chinchilla point cloud.

Slides 15-18 are deliberately three views of the *same* 245 runs plus the table that
checks they agree, so all four are generated here, from
results/chinchilla_runs.json (see scripts/chinchilla_data.py for where those runs come
from -- a reconstruction of the paper's Figure 4, not DeepMind's logs) and
results/chinchilla_paper.json (the paper's own published numbers).

    uv run python scripts/chinchilla_data.py            # once, writes the two JSONs
    uv run python scripts/chinchilla_slides.py          # fits, prints, writes results/
    uv run python scripts/chinchilla_slides.py --write  # + the four figures/*.md

The construction on each slide, and the beats it is revealed in:

  chinchilla-pareto (slide 15) -- Approach 1
      beat 0  loss against compute, one polyline per model size, log-log
      beat 1  the lower envelope of that family: the Pareto front
      beat 2  the family dimmed to 0.2, so only the front is left
      beat 3  a power law fitted to the front, its exponent set along it
      beat 4  N*(C) and D*(C): which model size owns which stretch of the front,
              as a staircase in the same colours, and the power law through it

  chinchilla-isoflop (slide 16) -- Approach 2, the same data sliced the other way
      beat 0  loss against model size at six of the paper's nine FLOP budgets
      beat 1  a parabola in log N per budget, its minimum marked
      beat 2  the envelope through the six minima
      beat 3  N*(C) and D*(C) from those minima, measured and fitted

  chinchilla-parametric (slide 17) -- Approach 3
      the paper's own five constants, no refitting: one surface drawn through the
      same six profiles, plus the compute-optimal ridge it implies

  chinchilla-exponents (slide 18)
      Table 2 of the paper, in the deck's `fit-matrix` style, with the deck's own
      measured exponents beside it and the Kaplan row last.

Which six model sizes and which six budgets is a choice, and it is made by rule rather
than by eye: the sizes are a factor-2.1 ladder from 175M to 6.8B among those with at
least seven reconstructed runs, and the budgets are the six of the paper's nine that
sit at 1 or 3 times a power of ten.  Every fitted number the slides show is printed by
this script, and the fits over all 43 sizes / all 9 budgets are printed next to them so
the effect of the choice is visible.
"""

from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from chinchilla_svg import RAMP, Panel, num, sup  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
RUNS = ROOT / "results/chinchilla_runs.json"
PAPER = ROOT / "results/chinchilla_paper.json"
FITS = ROOT / "results/chinchilla_fits.json"
FIGURES = ROOT / "figures"

# The six model sizes drawn on slide 15 and the six budgets on slides 16 and 17.
SIZES_M = (175, 425, 816, 1609, 2980, 6796)
BUDGETS = (1e19, 3e19, 1e20, 3e20, 1e21, 3e21)
# A run counts towards a budget if its reconstructed FLOP count is within 20 % of it,
# and towards that budget's parabola if its loss is within CUT nats of the profile's
# best -- the reconstruction contains runs an order of magnitude off the optimum
# (a 6.8B model on 245B tokens, loss 5.0) and a parabola in log N cannot hold both
# those and the bottom of the curve.
BUDGET_TOL = 0.08
CUT = 0.35

HEAD = ("<!-- generated by scripts/chinchilla_slides.py --write -- do not edit "
        "by hand -->\n<!-- Runs: 245 (N, C, loss) triples reconstructed from Figure 4\n"
        "     of Hoffmann et al. 2022 by Epoch AI (Besiroglu et al. 2024),\n"
        "     github.com/epoch-research/analyzing-chinchilla; model sizes snapped to\n"
        "     the paper's Table A9 and D = C/6N derived.  A figure reconstruction and\n"
        "     a subset of the paper's runs, NOT DeepMind's original logs.  Fitted\n"
        "     numbers: results/chinchilla_fits.json.  See scripts/chinchilla_data.py. -->")

W, H = 1180, 420


# ------------------------------------------------------------------ fitting


def power_fit(x, y) -> dict:
    """y = pref * x^exp by least squares in log-log, with its r^2."""
    lx, ly = np.log10(x), np.log10(y)
    exp, lp = np.polyfit(lx, ly, 1)
    r2 = float(np.corrcoef(lx, ly)[0, 1] ** 2)
    return {"exp": float(exp), "pref": float(10**lp), "r2": r2}


def by_size(runs) -> dict[float, tuple[np.ndarray, np.ndarray]]:
    """One (compute, loss) curve per model size, duplicate budgets averaged."""
    grouped: dict[float, dict] = collections.defaultdict(
        lambda: collections.defaultdict(list))
    for r in runs:
        grouped[r["n"]][round(np.log10(r["c"]), 3)].append(r["loss"])
    out = {}
    for n, d in grouped.items():
        ks = sorted(d)
        out[n] = (np.array([10.0**k for k in ks]),
                  np.array([float(np.mean(d[k])) for k in ks]))
    return out


def pareto(runs, sizes) -> dict:
    """Approach 1: the lower envelope of the per-model-size loss curves.

    The envelope is taken on a dense grid uniform in log C, each curve interpolated in
    log-log within its own compute range and nowhere outside it.  N*(C) then comes out
    as a staircase -- the model size that owns each stretch of the front -- and the
    power laws are least squares over that grid, which is the continuous L2 fit of a
    staircase and does not depend on how the six sizes happen to be spaced.
    """
    per_size = by_size(runs)
    curves = {n: per_size[n] for n in sizes}
    lo = min(c[0].min() for c in curves.values())
    hi = max(c[0].max() for c in curves.values())
    grid = np.geomspace(lo, hi, 2000)
    best = np.full(len(grid), np.inf)
    arg = np.zeros(len(grid))
    for n, (x, y) in curves.items():
        v = 10 ** np.interp(np.log10(grid), np.log10(x), np.log10(y),
                            left=np.nan, right=np.nan)
        m = ~np.isnan(v) & (v < best)
        best[m], arg[m] = v[m], n
    keep = np.isfinite(best)
    grid, best, arg = grid[keep], best[keep], arg[keep]

    # One contiguous run of the staircase per model size that ever wins.  The
    # envelope can hand a size back and forth (two curves crossing twice), so the
    # segment is the full span over which it wins, not the first stretch.
    segs = []
    for n in sizes:
        m = arg == n
        if not m.any():
            continue
        segs.append({"n": float(n), "c0": float(grid[m].min()),
                     "c1": float(grid[m].max())})
    return {
        "sizes": [float(n) for n in sizes],
        "curves": {f"{n:.6g}": {"c": x.tolist(), "loss": y.tolist()}
                   for n, (x, y) in curves.items()},
        "front": {"c": grid.tolist(), "loss": best.tolist(), "n": arg.tolist()},
        "segments": segs,
        "laws": {"l_of_c": power_fit(grid, best),
                 "n_of_c": power_fit(grid, arg),
                 "d_of_c": power_fit(grid, grid / (6 * arg))},
    }


def isoflop(runs, budgets, tol=BUDGET_TOL, cut=CUT) -> dict:
    """Approach 2: a parabola in log N per FLOP budget, and the six minima it gives."""
    profiles = []
    for b in budgets:
        d = collections.defaultdict(list)
        for r in runs:
            if abs(np.log10(r["c"] / b)) <= tol:
                d[r["n"]].append(r["loss"])
        ns = np.array(sorted(d))
        ls = np.array([float(np.mean(d[n])) for n in ns])
        keep = ls <= ls.min() + cut
        ns, ls = ns[keep], ls[keep]
        if len(ns) < 4:
            raise SystemExit(f"budget {b:.0e} keeps only {len(ns)} model sizes")
        q = np.polyfit(np.log10(ns), ls, 2)
        xm = -q[1] / (2 * q[0])
        if not np.log10(ns.min()) < xm < np.log10(ns.max()):
            raise SystemExit(f"budget {b:.0e} has its minimum outside the sweep")
        xs = np.linspace(np.log10(ns.min()) - 0.1, np.log10(ns.max()) + 0.1, 25)
        profiles.append({
            "c": float(b), "n": ns.tolist(), "loss": ls.tolist(),
            "n_star": float(10**xm), "loss_star": float(np.polyval(q, xm)),
            "d_star": float(b / (6 * 10**xm)),
            "curve": [[float(10**x), float(np.polyval(q, x))] for x in xs],
            "rms": float(np.std(ls - np.polyval(q, np.log10(ns)))),
        })
    c = np.array([p["c"] for p in profiles])
    return {
        "profiles": profiles,
        "laws": {"l_of_c": power_fit(c, [p["loss_star"] for p in profiles]),
                 "n_of_c": power_fit(c, [p["n_star"] for p in profiles]),
                 "d_of_c": power_fit(c, [p["d_star"] for p in profiles])},
    }


def law_curve(pm: dict, c: float, ns) -> list[list[float]]:
    """The paper's own surface, sliced at constant compute: L(N, C/6N)."""
    ns = np.asarray(ns, dtype=float)
    loss = (pm["E"] + pm["A"] * ns ** -pm["alpha"]
            + pm["B"] * (c / (6 * ns)) ** -pm["beta"])
    return [[float(n), float(l)] for n, l in zip(ns, loss)]


# ------------------------------------------------------------------ svg pieces


def pow10(v: float) -> str:
    """A power-of-ten axis label, 10 with a raised exponent."""
    return f"10{sup(f'{int(round(np.log10(v)))}', gap=1)}"


def legend(head: str, labels, colours=RAMP) -> str:
    spans = "\n".join(
        f'<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true">'
        f'<line x1="1" y1="5" x2="29" y2="5" stroke="{c}" stroke-width="2.2"/>'
        f'<circle cx="15" cy="5" r="2.8" fill="{c}"/></svg>{t}</span>'
        for t, c in zip(labels, colours))
    return (f'<div class="cap-legend">\n<span class="num">{head}</span>\n'
            f"{spans}\n</div>")


def row(head: str, labels, svg: str, cls: str = "") -> str:
    """Legend column, then the plot: the deck's .if-row, from the IsoFLOP slide.

    Vertical space is what runs out on these slides, and a legend line above the figure
    costs both its own height and none of the figure's -- running it down the left
    instead buys back about 60 px, which is the difference between the closing sentence
    fitting on the slide and not.
    """
    return (f'<div class="if-row cp-row {cls}">\n' + legend(head, labels) + "\n"
            + svg + "\n</div>")


def size_label(v: float) -> str:
    """A model size the way the paper writes it: 175M, 816M, 1.6B, 6.8B."""
    return f"{v / 1e9:.1f}B" if v >= 1e9 else f"{v / 1e6:.0f}M"


def svg_open(label: str, panels) -> list[str]:
    return [f'<svg class="plot-fig cp-fig" viewBox="0 0 {W} {H}" role="img" '
            f'aria-label="{label}">', "<defs>",
            *[p.defs() for p in panels], "</defs>"]


def fragment(index: int, inner: list[str]) -> list[str]:
    return [f'<g class="fragment" data-fragment-index="{index}">', *inner, "</g>"]


def panels_for(kind: str, x_left, y_left, x_right, y_top, y_bot):
    """The shared three-panel geometry: one wide panel, two stacked half-height ones.

    Slides 15 and 16 use the same boxes so the audience reads the second as a re-slicing
    of the first rather than as a new picture.
    """
    a = Panel(f"{kind}-a", 150, 640, 350, 18, x_left, y_left)
    b = Panel(f"{kind}-b", 820, 1160, 170, 18, x_right, y_top)
    c = Panel(f"{kind}-c", 820, 1160, 350, 200, x_right, y_bot)
    return a, b, c


BUDGET_HEAD = "<em>C</em> (&#215;10<sup>18</sup>)"


def right_pair(b: Panel, c: Panel, laws: dict, marks_b, marks_c,
               x_ticks, y_ticks_b=None, y_ticks_c=None) -> list[str]:
    """The two stacked panels: N*(C) above D*(C), sharing one compute axis.

    Explicit y ticks because the interesting stretch of either axis is often barely
    one decade wide, and decade ticks alone would label it once.
    """
    out: list[str] = []
    for p, key, ylab, ticks, marks in (
            (b, "n_of_c", 'model size <tspan class="pf-var">N</tspan>*', y_ticks_b,
             marks_b),
            (c, "d_of_c", 'dataset size <tspan class="pf-var">D</tspan>*', y_ticks_c,
             marks_c)):
        law = laws[key]
        lab = None if p is b else ('compute <tspan class="pf-var">C</tspan> (flops)')
        out += p.axes(lab, ylab, x_ticks,
                      ticks or [10.0**k for k in p.sy.decades()],
                      x_fmt=pow10, x_labels=p is c, ylab_dx=98, xlab_dy=62)
        line = p.power_line(law["pref"], law["exp"], p.sx.lo, p.sx.hi)
        out += p.clipped([f'<path class="pf-guide" d="{p.path(line)}"/>'])
        out += marks
        out.append(p.label_on(p.at(*line[0]), p.at(*line[-1]), 0.5,
                              '<tspan class="pf-var">C</tspan>',
                              f'{law["exp"]:.3f}', off=17))
    return out


# ------------------------------------------------------------------ slide 15


def pareto_svg(pf: dict) -> str:
    a, b, c = panels_for("pt", (4e18, 2.2e22), (2.02, 5.4),
                         (4e18, 2.2e22), (8.5e7, 1.7e10), (3.4e9, 4.4e11))
    label = ("Left: final loss against training compute, one line per model size, "
             "log-log; the lower envelope of the family is the compute-optimal Pareto "
             "front, and a power law is fitted to it. Right: the model size and the "
             "dataset size that own each stretch of that front, against compute, with "
             "their fitted power laws.")
    x_ticks = [1e19, 1e20, 1e21, 1e22]
    s = svg_open(label, (a, b, c))
    s += a.axes('compute <tspan class="pf-var">C</tspan> (flops)', "loss",
                x_ticks, (2.2, 2.5, 3.0, 4.0, 5.0), x_fmt=pow10,
                y_fmt=lambda v: f"{v:g}", ylab_dx=88, xlab_dy=62)

    # beat 0: the family.  Dimmed from beat 2 on by the .cp-fade rule in slides.css.
    fam = []
    for n, col in zip(pf["sizes"], RAMP):
        cur = pf["curves"][f"{n:.6g}"]
        pts = list(zip(cur["c"], cur["loss"]))
        fam.append(a.curve(pts, col, width=2.2))
        fam += [a.dot(x, y, col, r=3.4) for x, y in pts]
    s += ['<g class="cp-fade">', *a.clipped(fam), "</g>"]

    # beat 1: the front itself, over the same family
    front = pf["front"]
    step = [(x, y) for x, y in zip(front["c"], front["loss"])]
    s += fragment(1, a.clipped(
        [f'<path class="pf-front" d="{a.path(step[::12] + step[-1:])}"/>']))

    # beat 2: an empty group whose .visible state drives the dimming, nothing drawn
    s.append('<g class="cp-dim fragment" data-fragment-index="2"></g>')

    # beat 3: the power law through the front
    law = pf["laws"]["l_of_c"]
    line = a.power_line(law["pref"], law["exp"], 6e18, 1.6e22)
    s += fragment(3, a.clipped([f'<path class="pf-guide" d="{a.path(line)}"/>'])
                  + [a.label_on(a.at(*line[0]), a.at(*line[-1]), 0.72,
                                '<tspan class="pf-var">C</tspan>',
                                f'{law["exp"]:.3f}', off=30)])

    # beat 4: which size owns which stretch, as a staircase in the same colours
    marks_b, marks_c = [], []
    for seg, col in zip(pf["segments"], RAMP):
        n, c0, c1 = seg["n"], seg["c0"], seg["c1"]
        marks_b.append(b.curve([(c0, n), (c1, n)], col, width=3.4, cls="cp-tread"))
        marks_c.append(c.curve([(c0, c0 / (6 * n)), (c1, c1 / (6 * n))], col,
                               width=3.4, cls="cp-tread"))
    s += fragment(4, right_pair(b, c, pf["laws"],
                                b.clipped(marks_b), c.clipped(marks_c), x_ticks,
                                y_ticks_b=(1e8, 1e9, 1e10),
                                y_ticks_c=(1e10, 1e11)))
    s.append("</svg>")
    return "\n".join(s)


def pareto_md(pf: dict) -> str:
    labels = [size_label(n) for n in pf["sizes"]]
    return (HEAD + "\n\n"
            + row('model size <em>N</em>', labels, pareto_svg(pf)) + "\n")


# ------------------------------------------------------------------ slide 16


def isoflop_svg(iso: dict) -> str:
    a, b, c = panels_for("if", (4e7, 2.6e10), (2.15, 3.32),
                         (7e18, 5e21), (2.1e8, 6.5e9), (4.4e9, 2.4e11))
    label = ("Left: final loss against model size at six fixed compute budgets, each a "
             "U-shaped IsoFLOP profile with a parabola in log N fitted to it and its "
             "minimum marked; a dashed line runs through the six minima. Right: the "
             "model size and dataset size at those minima against compute, with their "
             "fitted power laws.")
    x_ticks = [1e19, 1e20, 1e21]
    s = svg_open(label, (a, b, c))
    s += a.axes('model size <tspan class="pf-var">N</tspan>', "loss",
                [10.0**k for k in a.sx.decades()], (2.2, 2.4, 2.6, 3.0),
                y_fmt=lambda v: f"{v:g}", ylab_dx=88, xlab_dy=62)

    # beat 0: the measurements
    for p, col in zip(iso["profiles"], RAMP):
        s += [a.dot(x, y, col, r=3.4) for x, y in zip(p["n"], p["loss"])]

    # beat 1: a parabola per budget, and where each one bottoms out
    par = []
    for p, col in zip(iso["profiles"], RAMP):
        par.append(a.curve(p["curve"], col, width=2.4))
    tips = [a.diamond(p["n_star"], p["loss_star"], col)
            for p, col in zip(iso["profiles"], RAMP)]
    s += fragment(1, a.clipped(par) + tips)

    # beat 2: the envelope through the minima
    env = [(p["n_star"], p["loss_star"]) for p in iso["profiles"]]
    s += fragment(2, a.clipped([f'<path class="pf-guide" d="{a.path(env)}"/>']))

    # beat 3: the same minima against their own compute
    marks_b = [b.diamond(p["c"], p["n_star"], col)
               for p, col in zip(iso["profiles"], RAMP)]
    marks_c = [c.diamond(p["c"], p["d_star"], col)
               for p, col in zip(iso["profiles"], RAMP)]
    s += fragment(3, right_pair(b, c, iso["laws"], marks_b, marks_c, x_ticks,
                               y_ticks_b=(3e8, 1e9, 3e9),
                               y_ticks_c=(1e10, 3e10, 1e11)))
    s.append("</svg>")
    return "\n".join(s)


def budget_label(v: float) -> str:
    """A budget in units of 1e18, so the legend reads 10, 30, 100, 300, 1k, 3k."""
    return num(round(v / 1e18))


def isoflop_md(iso: dict) -> str:
    labels = [budget_label(p["c"]) for p in iso["profiles"]]
    return HEAD + "\n\n" + row(BUDGET_HEAD, labels, isoflop_svg(iso)) + "\n"


# ------------------------------------------------------------------ slide 17

# Slide 17's figure sits in one of two equal columns, so it gets a box of its own
# rather than the three-panel one.  Narrow and tall: the six profiles are stacked
# vertically, so height is what they want, and a narrower viewBox at the same laid-out
# width is what makes the 20-unit tick type legible at half the slide.
PW, PH = 640, 600


def parametric_svg(iso: dict, paper: dict) -> str:
    """The paper's five constants, drawn through the six profiles they never saw.

    One panel, the same axes as slide 16's left panel: nothing is fitted here, so the
    figure's whole job is to let the audience check that a single surface passes through
    every profile at once.  The ridge is the compute-optimal locus the same constants
    imply, marked at each budget.
    """
    pm, imp = paper["parametric"], paper["parametric_implied"]
    p = Panel("pm-a", 100, 625, 520, 20, (4e7, 2.6e10), (2.15, 3.32))
    label = ("The five-constant Chinchilla loss surface sliced at the same six compute "
             "budgets, drawn through the measured IsoFLOP profiles, with the "
             "compute-optimal model size it implies marked on each slice.")
    s = [f'<svg class="plot-fig cp-fig" viewBox="0 0 {PW} {PH}" role="img" '
         f'aria-label="{label}">', "<defs>", p.defs(), "</defs>"]
    s += p.axes('model size <tspan class="pf-var">N</tspan>', "loss",
                [10.0**k for k in p.sx.decades()], (2.2, 2.4, 2.6, 3.0),
                y_fmt=lambda v: f"{v:g}", ylab_dx=66, xlab_dy=62)
    for prof, col in zip(iso["profiles"], RAMP):
        s += [p.dot(x, y, col, r=3.4) for x, y in zip(prof["n"], prof["loss"])]
    curves, tips = [], []
    for prof, col in zip(iso["profiles"], RAMP):
        c = prof["c"]
        lo = min(prof["n"]) / 1.6
        hi = max(prof["n"]) * 1.6
        curves.append(p.curve(law_curve(pm, c, np.geomspace(lo, hi, 40)), col,
                              width=2.4))
        n_s = imp["n_pref"] * c ** imp["n_exp"]
        tips.append(p.diamond(n_s, pm["E"] + pm["A"] * n_s ** -pm["alpha"]
                              + pm["B"] * (c / (6 * n_s)) ** -pm["beta"], col))
    s += fragment(1, p.clipped(curves))
    ridge = []
    for prof in iso["profiles"]:
        c = prof["c"]
        n_s = imp["n_pref"] * c ** imp["n_exp"]
        ridge.append((n_s, pm["E"] + pm["A"] * n_s ** -pm["alpha"]
                      + pm["B"] * (c / (6 * n_s)) ** -pm["beta"]))
    s += fragment(2, p.clipped([f'<path class="pf-guide" d="{p.path(ridge)}"/>'])
                  + tips)
    s.append("</svg>")
    return "\n".join(s)


def parametric_md(iso: dict, paper: dict) -> str:
    labels = [budget_label(prof["c"]) for prof in iso["profiles"]]
    return (HEAD + "\n\n"
            + row(BUDGET_HEAD, labels, parametric_svg(iso, paper), "cp-row-pm")
            + "\n")


# ------------------------------------------------------------------ slide 18


def exponents_md(pf: dict, iso: dict, paper: dict) -> str:
    """Table 2 of the paper, plus what the deck's own fits got, in `fit-matrix` style.

    Four rows, revealed in three beats: the three approaches together (they agree), then
    the Kaplan row (it does not).  The measured column is this deck's refit of the
    reconstruction, so the audience can see the same numbers come out of the data on
    the two previous slides.
    """
    t2 = {r["approach"]: r for r in paper["table_2"]}
    imp = paper["parametric_implied"]
    mine = {"1. Pareto front": (pf["laws"]["n_of_c"]["exp"],
                                pf["laws"]["d_of_c"]["exp"]),
            "2. IsoFLOP": (iso["laws"]["n_of_c"]["exp"],
                           iso["laws"]["d_of_c"]["exp"]),
            "3. Parametric fit": (imp["n_exp"], imp["d_exp"])}
    def cell(cls: str, step: int, text: str) -> str:
        return (f'<div class="{cls} fragment" data-fragment-index="{step}">'
                f"{text}</div>")

    # The row divider is a full-width grid item of its own rather than a border on each
    # cell: the cells are fragments, and a border on a not-yet-revealed cell is
    # invisible too, which leaves the rules stopping halfway across the table on the
    # first two clicks.
    rule = '<div class="fm-rule"></div>\n'
    rows = []
    for key in ("1. Pareto front", "2. IsoFLOP", "3. Parametric fit"):
        r, (ma, mb) = t2[key], mine[key]
        rows.append(rule
                    + cell("fm-label fm-navy", 1, key)
                    + cell("fm-value", 1, f'{r["a"]:.2f}')
                    + cell("fm-value", 1, f'{r["b"]:.2f}')
                    + cell("fm-value fm-soft", 2, f"{ma:.2f}")
                    + cell("fm-value fm-soft", 2, f"{mb:.2f}"))
    k = t2["Kaplan et al. (2020)"]
    rows.append(rule
                + cell("fm-label fm-red", 3, "Kaplan et al.")
                + cell("fm-value fm-red", 3, f'{k["a"]:.2f}')
                + cell("fm-value fm-red", 3, f'{k["b"]:.2f}')
                + cell("fm-value fm-soft", 3, "--")
                + cell("fm-value fm-soft", 3, "--"))
    body = "\n".join(rows)
    return f"""{HEAD}

<div class="fit-matrix chin-matrix">
<div></div>
<div class="fm-group">Chinchilla paper</div><div class="fm-group">redone here</div>
<div></div>
<div class="fm-head"><em>a</em></div><div class="fm-head"><em>b</em></div>
<div class="fm-head fm-soft"><em>a</em></div><div class="fm-head fm-soft"><em>b</em></div>
{body}
</div>

<div class="inline-footnote">

$N^*\\propto C^{{a}}$, $D^*\\propto C^{{b}}$. Left pair: Table 2 of
[@hoffmann2022training]. Right pair: the same three constructions, redone here.

</div>
"""


# ------------------------------------------------------------------ driver


def report(pf: dict, iso: dict, paper: dict, runs) -> None:
    print("Approach 1, Pareto front over "
          f"{len(pf['sizes'])} model sizes ({', '.join(num(n) for n in pf['sizes'])})")
    for seg in pf["segments"]:
        print(f"    {num(seg['n']):>7s} owns the front over C = "
              f"{seg['c0']:.2e}..{seg['c1']:.2e}")
    for k, v in pf["laws"].items():
        print(f"    {k:8s} exponent {v['exp']:+.4f}  r2 {v['r2']:.4f}")
    all_pf = pareto(runs, sorted({r["n"] for r in runs}))
    print("    over all 43 sizes: "
          + ", ".join(f"{k} {v['exp']:+.4f}" for k, v in all_pf["laws"].items()))

    print("\nApproach 2, IsoFLOP profiles")
    for p in iso["profiles"]:
        print(f"    C = {p['c']:.0e}  {len(p['n']):2d} sizes  N* = {num(p['n_star']):>7s}"
              f"  D* = {num(p['d_star']):>7s}  L* = {p['loss_star']:.4f}  "
              f"rms {p['rms']:.4f}  {p['d_star'] / p['n_star']:.0f} tokens/param")
    for k, v in iso["laws"].items():
        print(f"    {k:8s} exponent {v['exp']:+.4f}  r2 {v['r2']:.4f}")
    all_iso = isoflop(runs, json.loads(RUNS.read_text())["isoflop_budgets"])
    print("    over all 9 budgets: "
          + ", ".join(f"{k} {v['exp']:+.4f}" for k, v in all_iso["laws"].items()))

    imp = paper["parametric_implied"]
    print("\nApproach 3, the paper's own constants")
    print(f"    N* ~ C^{imp['n_exp']:.4f}, D* ~ C^{imp['d_exp']:.4f}, "
          f"L-L_inf ~ C^{imp['l_exp']:.4f}")
    print("\nTable 2 of the paper: "
          + "; ".join(f"{r['approach']} a={r['a']} b={r['b']}"
                      for r in paper["table_2"]))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true",
                    help="write the four figures/chinchilla-*.md files")
    args = ap.parse_args()

    store = json.loads(RUNS.read_text())
    paper = json.loads(PAPER.read_text())
    runs = store["runs"]
    sizes = [float(m) * 1e6 for m in SIZES_M]
    missing = [n for n in sizes if n not in {r["n"] for r in runs}]
    if missing:
        raise SystemExit(f"model sizes {missing} are not in the reconstruction")

    pf = pareto(runs, sizes)
    iso = isoflop(runs, BUDGETS)
    report(pf, iso, paper, runs)

    FITS.write_text(json.dumps({"source": store["source"], "pareto": pf,
                                "isoflop": iso, "paper": paper}, indent=1))
    print(f"\nwrote {FITS.relative_to(ROOT)}")

    if args.write:
        for key, body in (("chinchilla-pareto", pareto_md(pf)),
                          ("chinchilla-isoflop", isoflop_md(iso)),
                          ("chinchilla-parametric", parametric_md(iso, paper)),
                          ("chinchilla-exponents", exponents_md(pf, iso, paper))):
            (FIGURES / f"{key}.md").write_text(body)
            print(f"wrote figures/{key}.md")


if __name__ == "__main__":
    main()
