"""Emergence: a smooth loss made of per-band accuracy steps.

The (N, D) scan measures one number, the excess loss averaged over the whole Zipf tail,
and it is a clean power law in both N and D.  This script re-measures the *same* runs
with a threshold metric on a narrow slice of contexts -- uniform top-1 accuracy on
context indices 1-1k, 2-3k, 5-6k, 10-11k and 20-30k -- and gets sigmoids that switch on
one after another as the model grows or as training proceeds.

    PYTHONPATH=src uv run python scripts/emergence.py --run        # ~70 min
    PYTHONPATH=src uv run python scripts/emergence.py --run --hs 32 64 --steps 6400
    PYTHONPATH=src uv run python scripts/emergence.py --report     # midpoints + table
    PYTHONPATH=src uv run python scripts/emergence.py --figures    # figures/emergence.png
    PYTHONPATH=src uv run python scripts/emergence.py --slide      # chart block to stdout
    PYTHONPATH=src uv run python scripts/emergence.py --write-slide

The chart block always goes to results/emergence_chart.md (and, with --slide, to stdout).
--write-slide additionally writes

    figures/emergence-chart.md    the deck's figure: legend, chart and styling script

which is what the `<!-- figure: emergence-chart -->` placeholder on "Digression: emergent
behavior under the hood" pulls in when scripts/build_slides.py expands it.  Nothing about
the plot lives in slides.md, so this script owns the figure outright.

Runs are billed to their own ledger (results/emergence_ledger.jsonl, no budget) and
checkpointed to results/emergence.json after every h, so the sweep is resumable.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
import time

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from assocmem import ledger  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "results/emergence.json"
CHART = ROOT / "results/emergence_chart.md"
# The deck's copy of the plot.  slides.md holds a `<!-- figure: emergence-chart -->`
# placeholder that scripts/build_slides.py expands with this file, so the figure -- chart,
# legend and styling tag -- is written here and edited nowhere else.
FIGURE = ROOT / "figures/emergence-chart.md"
FIGURE_HEAD = ("<!-- generated by scripts/emergence.py --write-slide "
               "-- do not edit by hand -->")
FIG = ROOT / "figures/emergence.png"
LEDGER = ROOT / "results/emergence_ledger.jsonl"

# Not the student exercise: its own ledger, no budget, and the closed 1e13 ledger in
# results/ledger.jsonl is never touched.
ledger.configure(path=LEDGER, budget=float("inf"))

from assocmem import emergence as E  # noqa: E402
from assocmem.data import D_OUT  # noqa: E402
from assocmem.grid import bin_mass, build_strat_eval  # noqa: E402
from assocmem.grid_fit import CAP_PER_H, lr_surface  # noqa: E402
from assocmem.problem import get_stream  # noqa: E402

HS = (32, 64, 128, 256, 512, 1024, 2048, 4096, 8192)
STEPS = 409_600  # the whole stream: D = 26.2M tokens, the scan's top data rung
SEED = 0

# One ordered ramp over the five bands, light (head) to dark (tail), from the deck.
COLORS = ("#86b6ef", "#5598e7", "#2a78d6", "#184f95", "#0d366b")
# Only the model-size chart goes on a slide, and it is one block, so there is nothing to
# label or delimit: the figure file is this script's output whole.  The over-training
# curves stay in the JSON and in figures/emergence.png -- this model shows the ordering
# over training too, but not as a *sudden* switch, so it is not the deck's point.
STYLE_SCRIPT = '<script src="assets/emergence-chart.js"></script>'


def key(h: int, steps: int, seed: int) -> str:
    return f"h{h}/s{steps}/z{seed}"


def load() -> dict:
    return json.loads(OUT.read_text()) if OUT.exists() else dict(meta={}, runs={})


def save(store: dict) -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.partial")
    tmp.write_text(json.dumps(store, indent=1))
    tmp.rename(OUT)


# ------------------------------------------------------------------ analysis


def band_mid(k: int) -> float:
    """Median context index of band k: where a cutoff sits when the band is half learned.

    The band is weighted *uniformly*, so 50 % accuracy means the learned/not-learned
    cutoff has reached the arithmetic middle of the band -- not its geometric middle.
    """
    a, b = E.BANDS[k]
    return 0.5 * (a + b - 1)


def crossing(xs, ys, level: float = 0.5) -> float | None:
    """Where the accuracy curve first reaches `level`, log-interpolated in x."""
    xs, ys = np.asarray(xs, float), np.asarray(ys, float)
    hit = np.nonzero(ys >= level)[0]
    if len(hit) == 0 or hit[0] == 0:
        return None
    i = hit[0]
    y0, y1 = ys[i - 1], ys[i]
    t = (level - y0) / (y1 - y0)
    return float(np.exp(np.log(xs[i - 1]) + t * (np.log(xs[i]) - np.log(xs[i - 1]))))


def sweep_series(store: dict, steps: int = STEPS, seed: int = SEED):
    """(hs, N, top1 (n_h, n_bands), sampled, excess) at the last checkpoint of each h."""
    runs = [r for r in store["runs"].values() if r["steps"] == steps and r["seed"] == seed]
    runs.sort(key=lambda r: r["h"])
    hs = [r["h"] for r in runs]
    last = [r["curve"][-1] for r in runs]
    return (np.array(hs), D_OUT * np.array(hs, float),
            np.array([c["top1"] for c in last]),
            np.array([c["sampled"] for c in last]),
            np.array([c.get("excess", np.nan) for c in last]))


def curve_series(store: dict, h: int, steps: int = STEPS, seed: int = SEED):
    """(tokens, top1 (n_ckpt, n_bands), sampled, excess) along one run."""
    r = store["runs"][key(h, steps, seed)]
    c = r["curve"]
    return (np.array([x["tokens"] for x in c], float),
            np.array([x["top1"] for x in c]),
            np.array([x["sampled"] for x in c]),
            np.array([x.get("excess", np.nan) for x in c]))


def report(store: dict, steps: int = STEPS) -> dict:
    hs, n, top1, samp, ex = sweep_series(store, steps)
    hmax = int(hs[-1])
    d, ct, cs, cex = curve_series(store, hmax, steps)

    print(f"\nper-band top-1 accuracy vs model size, at D = {64 * steps / 1e6:.1f}M tokens")
    print(f"  {'N':>9s} " + "".join(f"{lab:>9s}" for lab in E.LABELS) + "   excess")
    for i, h in enumerate(hs):
        print(f"  {int(D_OUT * h):>9d} " + "".join(f"{v:9.3f}" for v in top1[i])
              + f"   {ex[i]:.4f}")

    out = dict(bands=list(E.LABELS), steps=steps, hs=[int(x) for x in hs], rows=[])
    print("\nswitch-on: model size N at which the band reaches 10/50/90 % accuracy")
    print(f"  {'band':>8s} {'mid i':>8s} {'N(10%)':>10s} {'N(50%)':>10s} {'N(90%)':>10s}"
          f" {'decades':>8s} {'N_pred':>10s} {'ratio':>7s}")
    for k, lab in enumerate(E.LABELS):
        c10, c50, c90 = (crossing(n, top1[:, k], q) for q in (0.1, 0.5, 0.9))
        mid = band_mid(k)
        npred = D_OUT * mid / CAP_PER_H  # capacity(N) = CAP_PER_H * h contexts
        row = dict(band=lab, mid=mid, n10=c10, n50=c50, n90=c90, n_pred=npred,
                   ratio=(c50 / npred if c50 else None),
                   decades=(np.log10(c90 / c10) if c10 and c90 else None))
        out["rows"].append(row)
        def g(v, w=10, p=0):
            return f"{v:{w}.{p}f}" if v else " " * (w - 1) + "-"
        print(f"  {lab:>8s} {mid:8.0f} {g(c10)} {g(c50)} {g(c90)}"
              f" {g(row['decades'], 8, 2)} {g(npred)} {g(row['ratio'], 7, 2)}")

    print(f"\nover training, h = {hmax} (N = {D_OUT * hmax:,}):"
          f" tokens D at which the band reaches 50 %")
    print(f"  {'band':>8s} {'final':>7s} {'D(50%)':>10s} {'D(seen once)':>13s}"
          f" {'times seen':>11s}")
    for k, lab in enumerate(E.LABELS):
        c50 = crossing(d, ct[:, k], 0.5)
        mid = band_mid(k)
        # "seen once" coverage: p(mid) * D = 1, i.e. D = mid^alpha up to the zeta factor
        pmid = bin_mass(mid, mid + 1)
        dcov = 1.0 / pmid
        row = dict(band=lab, final=float(ct[-1, k]), d50=c50, d_cover=dcov,
                   times_seen=(c50 * pmid if c50 else None))
        out["rows"][k].update(row)
        print(f"  {lab:>8s} {ct[-1, k]:7.3f} "
              + (f"{c50:10.3g} {dcov:13.3g} {c50 * pmid:11.1f}" if c50 else
                 f"{'never':>10s} {dcov:13.3g} {'-':>11s}"))
    out["largest"] = dict(h=hmax, tokens=list(d), top1=ct.tolist(),
                          sampled=cs.tolist(), excess=cex.tolist())
    span = np.nanmax(ex) / np.nanmin(ex)
    print(f"\nmacro view, same runs: excess loss falls smoothly from {np.nanmax(ex):.4f}"
          f" to {np.nanmin(ex):.4f} nats ({span:.2f}x) over the same {len(hs)} models.")
    return out


# ------------------------------------------------------------------ figure


def figures(store: dict, steps: int = STEPS) -> None:
    """Six panels: the sharp view and the smooth view of the same nine runs.

    The training axis is drawn twice, linear and logarithmic.  Linear is the honest
    picture of *when* a band switches on -- the rare bands take most of the run -- but it
    crushes the head bands into the left edge, which the log axis undoes.
    """
    import matplotlib as mpl
    import matplotlib.pyplot as plt

    from assocmem.plots import ACCENT, INK2, INK3, STYLE, SURFACE

    hs, n, top1, samp, ex = sweep_series(store, steps)
    hmax = int(hs[-1])
    d, ct, cs, cex = curve_series(store, hmax, steps)

    with mpl.rc_context(STYLE):
        fig, ax = plt.subplots(2, 3, figsize=(14.4, 7.4))
        (a, b, c), (e, f, g) = ax

        for k, lab in enumerate(E.LABELS):
            a.plot(n, top1[:, k], "o-", ms=4.5, lw=1.8, color=COLORS[k], label=lab,
                   mec=SURFACE, mew=1.0)
            a.axvline(D_OUT * band_mid(k) / CAP_PER_H, color=COLORS[k], lw=1.0, ls=":",
                      alpha=0.75, zorder=0)
            b.plot(d / 1e6, ct[:, k], "-", lw=1.8, color=COLORS[k])
            c.plot(d, ct[:, k], "-", lw=1.8, color=COLORS[k])
        a.set(xscale="log", xlabel="model size $N = 512h$", ylabel="top-1 accuracy",
              ylim=(-0.03, 1.03),
              title=f"(a) accuracy per context band, $D$ = {64 * steps / 1e6:.1f}M tokens")
        proxy = mpl.lines.Line2D([], [], color=INK3, ls=":", lw=1.0)
        a.legend([*a.get_lines()[:len(E.LABELS)], proxy],
                 [*E.LABELS, "capacity $=$ band median"], title="context index",
                 fontsize=7, title_fontsize=7, labelcolor=INK2, ncol=2, loc="upper left",
                 frameon=True, facecolor=SURFACE, edgecolor="none", framealpha=0.85)

        b.set(xlabel="training tokens $D$ (millions)", ylabel="top-1 accuracy",
              ylim=(-0.03, 1.03), xlim=(0, d[-1] / 1e6),
              title=f"(b) accuracy over training, $h$ = {hmax}")
        c.set(xscale="log", xlabel="training tokens $D$", ylabel="top-1 accuracy",
              ylim=(-0.03, 1.03), title="(c) same, on a log axis")

        # The macro view of the very same runs: no steps anywhere.
        e.plot(n, ex, "o-", ms=5, lw=1.8, color=ACCENT, mec=SURFACE, mew=1.0)
        e.set(xscale="log", yscale="log", xlabel="model size $N = 512h$",
              ylabel="$L - L_\\infty$ (nats)", title="(d) the loss (a) averages to")
        f.plot(d / 1e6, cex, "-", lw=1.8, color=ACCENT)
        f.set(xlabel="training tokens $D$ (millions)", ylabel="$L - L_\\infty$ (nats)",
              xlim=(0, d[-1] / 1e6), title="(e) the loss (b) averages to")
        g.plot(d, cex, "-", lw=1.8, color=ACCENT)
        g.set(xscale="log", yscale="log", xlabel="training tokens $D$",
              ylabel="$L - L_\\infty$ (nats)", title="(f) same, log-log")

        fig.suptitle("A smooth scaling law is a sum of sharp per-context switches",
                     fontsize=11, y=0.985)
        fig.tight_layout(rect=(0, 0, 1, 0.96))
        FIG.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(FIG, dpi=170)
        print(f"wrote {FIG}")


# ------------------------------------------------------------------ slide


def _points(pts, dp: int = 3) -> str:
    return "\n".join(f"        - {{x: {x:.4g}, y: {y:.{dp}f}}}" for x, y in pts)


def _axis(name, label, kind, lo, hi, extra=()):
    out = [f"    {name}:", f"      type: {kind}",
           f'      title: {{display: true, text: "{label}"}}',
           f"      min: {lo:.4g}", f"      max: {hi:.4g}",
           "      grid: {drawOnChartArea: false}", "      ticks: {padding: 8}"]
    return out + list(extra)


def chart_block(series, xlabel, xkind, xlo, xhi) -> str:
    lines = ["```chart", "type: line", "data:", "  datasets:"]
    for (lab, pts), col in zip(series, COLORS):
        lines += [f'    - label: "{lab}"', f'      color: "{col}"', "      data:",
                  _points(pts)]
    lines += ["options:", "  plugins:", "    legend: {display: false}", "  scales:"]
    lines += _axis("x", xlabel, xkind, xlo, xhi)
    lines += _axis("y", "top-1 accuracy", "linear", 0, 1)
    lines.append("```")
    return "\n".join(lines)


def legend_html() -> str:
    """Five swatches on one line, after a single muted "ranks" heading.

    The slide is a 1/1 split, so the legend gets half a slide: spelling out "contexts
    1-1k ... contexts 20-30k" wrapped onto a second line and pushed the plot down, and so
    did "context ranks" as a heading.  One short word carries it -- the prose beside the
    plot already says the bands are bands of context ranks.
    """
    spans = "\n".join(
        f'<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true">'
        f'<line x1="1" y1="5" x2="29" y2="5" stroke="{c}" stroke-width="2.2"/>'
        f'<circle cx="15" cy="5" r="2.8" fill="{c}"/></svg>{lab}</span>'
        for lab, c in zip(E.LABELS, COLORS))
    head = '<span class="legend-note">ranks</span>'
    return f'<div class="cap-legend">\n{head}\n{spans}\n</div>'


def slide_body(store: dict, steps: int = STEPS) -> str:
    """The legend, the chart and its styling tag, as they appear on the slide.

    The `<script src>` pass runs at parse time and only sees the canvases parsed so far,
    so the tag has to come *after* the chart block.
    """
    _, n, top1, _, _ = sweep_series(store, steps)
    # the x range starts at a power of ten so that the drawn 10^k ticks land inside it
    chart = chart_block([(lab, list(zip(n, top1[:, k])))
                         for k, lab in enumerate(E.LABELS)], "model size N",
                        "logarithmic", 10 ** np.floor(np.log10(n[0])), n[-1] * 1.4)
    return "\n".join([legend_html(), "", chart, "", STYLE_SCRIPT])


def write_figure(store: dict, steps: int = STEPS) -> None:
    """Write figures/emergence-chart.md, the figure the deck's placeholder pulls in.

    The legend and the styling script go in with the plot: they belong to the chart, not
    to the prose beside it, and keeping them together is what stops the legend from
    drifting away from the series it names.
    """
    FIGURE.parent.mkdir(parents=True, exist_ok=True)
    FIGURE.write_text(FIGURE_HEAD + "\n\n" + slide_body(store, steps) + "\n")


# ------------------------------------------------------------------ run


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", action="store_true", help="train the sweep")
    ap.add_argument("--hs", nargs="*", type=int, default=list(HS))
    ap.add_argument("--steps", type=int, default=STEPS)
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--lr", type=float, help="override the lr surface (one value)")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--figures", action="store_true")
    ap.add_argument("--slide", action="store_true",
                    help="print the chart block (and write results/emergence_chart.md)")
    ap.add_argument("--write-slide", action="store_true",
                    help="also write figures/emergence-chart.md, the deck's figure")
    args = ap.parse_args()

    store = load()
    if args.report:
        store["analysis"] = report(store, args.steps)
        save(store)
    if args.figures:
        figures(store, args.steps)
    if args.slide or args.write_slide:
        body = slide_body(store, args.steps)
        CHART.write_text(body + "\n")
        if args.slide:
            print(body)
        print(f"wrote {CHART}")
        if args.write_slide:
            write_figure(store, args.steps)
            print(f"wrote {FIGURE}")
    if not args.run:
        if not (args.report or args.figures or args.slide or args.write_slide):
            ap.error("give --run, --report, --figures or --slide")
        return

    todo = [h for h in args.hs if key(h, args.steps, args.seed) not in store["runs"]]
    if not todo:
        print("nothing to do (all runs present)")
        return

    be = E.build_band_eval()
    se = build_strat_eval()
    lr_fn = lr_surface(json.loads((ROOT / "results/grid.json").read_text()))
    ckpts = E.checkpoints(args.steps)
    store["meta"] = dict(bands=[list(b) for b in E.BANDS], labels=list(E.LABELS),
                         band_sizes=be.sizes, m_band=len(be), l_inf=se.l_inf,
                         cap_per_h=CAP_PER_H, checkpoints=ckpts,
                         lr_surface=dict(coef=list(lr_fn.coef), rms=lr_fn.rms,
                                         n=lr_fn.n) if lr_fn else None)
    plan = sum(6 * D_OUT * h * 64 * args.steps for h in todo)
    print(f"bands {be.labels} -> {be.sizes} contexts ({len(be)} total)")
    print(f"{len(todo)} runs, {len(ckpts)} checkpoints each, ~{plan:.2e} flops "
          f"(~{plan / 3.5e11 / 60:.0f} min at 350 GFLOP/s)")

    t0 = time.time()
    stream = get_stream(64 * args.steps)
    print(f"stream loaded in {time.time() - t0:.0f} s\n")
    print(f"  {'run':>18s} {'lr':>8s} {'excess':>8s}  "
          + "".join(f"{lab:>8s}" for lab in E.LABELS) + f" {'s':>7s}")
    t0 = time.time()
    for h in todo:
        lr = args.lr if args.lr else lr_fn(h, args.steps)
        r = E.run_curve(h, args.steps, lr, stream, be, se, seed=args.seed, ckpts=ckpts)
        store["runs"][key(h, args.steps, args.seed)] = r
        save(store)
        last = r["curve"][-1]
        print(f"  {key(h, args.steps, args.seed):>18s} {lr:8.5f} "
              f"{last.get('excess', float('nan')):8.4f}  "
              + "".join(f"{v:8.3f}" for v in last["top1"]) + f" {r['seconds']:7.1f}",
              flush=True)
    print(f"\ndone in {(time.time() - t0) / 60:.1f} min.  "
          f"{len(store['runs'])} runs in {OUT}")
    print(ledger.report().splitlines()[0])


if __name__ == "__main__":
    main()
