"""Generate the two scaling-law result slides.

The first fits the cheap (N, D) corner and reports interpolation plus a genuine
held-out test at roughly one order of magnitude more compute. The second compares
the two local loss exponents with their alpha-dependent predictions.

    PYTHONPATH=src uv run python scripts/grid_slide.py
    PYTHONPATH=src uv run python scripts/grid_slide.py --write-slide

Both blocks always go to results/grid_chart.md.  --write-slide puts them into the deck,
each where it belongs:

    figures/results-alpha.md    the exponents-vs-alpha chart (legend and styling script
                                included), pulled in by the slide's
                                `<!-- figure: results-alpha -->` placeholder
    slides.md                   the results-fit block -- prose and a table of fitted
                                percentages, no axes, so it stays inline between its
                                markers
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from assocmem.grid_fit import cells_of, fit_law, grid_means  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "results/grid_chart.md"
SLIDES = ROOT / "slides.md"
A_HS = (32, 64, 128, 256, 512)
A_STEPS = (100, 400, 1600, 6400, 25_600)

NAVY, RED = "#0f3460", "#c0392b"
# The chart is a file of its own, expanded into the deck by scripts/build_slides.py;
# the fit block is prose plus a table, so it stays inline between markers.
FIGURE = ROOT / "figures/results-alpha.md"
FIGURE_HEAD = ("<!-- generated by scripts/grid_slide.py --write-slide "
               "-- do not edit by hand -->")
MARKS = {
    "results-fit": (
        "<!-- BEGIN results-fit (generated by scripts/grid_slide.py) -->",
        "<!-- END results-fit -->",
    ),
}


def fit_numbers(store: dict) -> dict:
    n, d, y, *_ = cells_of(store, A_HS, A_STEPS)
    laws = {f: fit_law(n, d, y, form=f) for f in ("additive", "power_mean")}
    c_fit_max = float(6 * n.max() * d.max())

    # The grid is geometric, so no cells sit at exactly 10x. The four held-out
    # cells at 8x and 16x bracket one decade without interpolation.
    means = grid_means(store)
    held = [k for k in means if k[0] not in A_HS or k[1] not in A_STEPS]
    decade = [k for k in held
              if 8 * c_fit_max <= 6 * 512 * k[0] * 64 * k[1] <= 16 * c_fit_max]

    def held_rms(law) -> float:
        err = [np.log(float(law.predict(512 * h, 64 * s)) / means[(h, s)])
               for h, s in decade]
        return float(np.sqrt(np.mean(np.square(err))))

    return dict(
        n_fit=len(y), n_test=len(decade), c_fit_max=c_fit_max,
        add=laws["additive"], coupled=laws["power_mean"],
        add_test=held_rms(laws["additive"]),
        coupled_test=held_rms(laws["power_mean"]),
    )


def fit_md(v: dict) -> str:
    """The prose and the two-row table, with the deck's reveal markers baked in.

    The slide shows the Chinchilla row on the first click and the coupled-law
    column plus the Skaling row on the second, so the fragment attributes have to
    survive a regeneration -- hence they are written here rather than patched into
    slides.md by hand.  A `fit-matrix` row is three grid cells, so the reveal is
    marked on each cell: wrapping them would take the row out of the grid.  Only
    the two labels carry `data-colloquium-fragment="1"` (colloquium renumbers every
    occurrence of that exact attribute in document order, so it is a marker, not an
    index); their values carry the resulting index outright, and so does the
    `chin-story` column in slides.md.
    """
    return f"""
Fit on **{v['n_fit']} low-compute runs**, then test on {v['n_test']} held-out runs
at $8$--$16\\times$ the fitting budget.

<div class="fit-matrix">
<div></div><div class="fm-head">fit region</div><div class="fm-head">extrapolation</div>
<div class="fm-label fm-red fragment" data-colloquium-fragment="1">Chinchilla</div><div class="fm-value fm-red fragment" data-fragment-index="1">{100 * v['add'].rmse_log:.1f}%</div><div class="fm-value fm-red fragment" data-fragment-index="1">{100 * v['add_test']:.1f}%</div>
<div class="fm-label fm-navy fragment" data-colloquium-fragment="1">Skaling</div><div class="fm-value fm-navy fragment" data-fragment-index="2">{100 * v['coupled'].rmse_log:.1f}%</div><div class="fm-value fm-navy fragment" data-fragment-index="2">{100 * v['coupled_test']:.1f}%</div>
</div>

<div class="inline-footnote">

Relative rms error on $L-L_\\infty$; $L_\\infty$ is known.

</div>
"""


def alpha_chart_md(rows: list[dict]) -> str:
    """Measured local slopes versus alpha, with any under-resolved point explicit."""
    g = np.linspace(1.05, max(r["alpha"] for r in rows) + 0.05, 24)
    alpha = [r["alpha"] for r in rows]
    a_vals = [r.get("a_ext", r["a"]) for r in rows]
    # A row is a bound, not a measurement, when even the pair it is read from sits too
    # close to its capacity for the model to be the binding constraint.  Same threshold
    # as alpha_sweep.MARGIN_MIN, which is what picks that pair.
    bound = [r.get("a_ext_margin", r["margin"]) < 10.0 for r in rows]
    reliable_a = [(x, y) for x, y, b in zip(alpha, a_vals, bound) if not b]
    limited_a = [(x, y) for x, y, b in zip(alpha, a_vals, bound) if b]

    def pts(x, y=None):
        pairs = x if y is None else zip(x, y)
        return "\n".join(f"        - {{x: {u:.4g}, y: {v:.4f}}}" for u, v in pairs)

    # The hollow marker only earns a legend entry when there is one to explain.
    model_key = (
        f'<circle cx="11" cy="5" r="3.2" fill="{NAVY}"/>'
        f'<circle cx="22" cy="5" r="3.2" fill="white" stroke="{NAVY}" stroke-width="1.8"/>'
        f'</svg>model <span class="legend-note">(open = lower bound)</span>'
        if limited_a else
        f'<circle cx="15" cy="5" r="3.2" fill="{NAVY}"/></svg>model limited'
    )

    # An empty dataset would still draw a legend-less entry and a null `data:` key.
    bound_ds = "" if not limited_a else (
        f'    - label: "measured lower bound, model axis"\n'
        f'      color: "{NAVY}"\n'
        f'      data:\n{pts(limited_a)}\n'
    )

    return f"""
<div class="cap-legend">
<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true">{model_key}</span>
<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true"><circle cx="15" cy="5" r="3.2" fill="{RED}"/></svg>data limited</span>
<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true"><line x1="1" y1="5" x2="29" y2="5" stroke="#9ca3af" stroke-width="1.5" stroke-dasharray="6 5"/></svg>theory</span>
</div>

```chart
type: line
data:
  datasets:
    - label: "measured, model axis"
      color: "{NAVY}"
      data:
{pts(reliable_a)}
{bound_ds}    - label: "theory, model axis"
      color: "{NAVY}"
      data:
{pts(g, g - 1.0)}
    - label: "measured, data axis"
      color: "{RED}"
      data:
{pts(alpha, [r['b'] for r in rows])}
    - label: "theory, data axis"
      color: "{RED}"
      data:
{pts(g, 1.0 - 1.0 / g)}
options:
  plugins:
    legend: {{display: false}}
  scales:
    x:
      type: linear
      title: {{display: true, text: "tail exponent alpha"}}
      min: 1.02
      max: {max(alpha) + 0.08:.2f}
      grid: {{drawOnChartArea: false}}
      ticks: {{padding: 8}}
    y:
      type: linear
      title: {{display: true, text: "loss exponent"}}
      min: 0
      max: 0.92
      grid: {{drawOnChartArea: false}}
      ticks: {{padding: 8}}
```

<script src="assets/results-chart.js"></script>
"""


def write_figure(body: str) -> None:
    """Write figures/results-alpha.md: the chart, its legend and its styling script.

    The legend and the `<script>` tag travel with the chart -- they describe the
    series it draws, so leaving them in slides.md would let the two drift apart.
    """
    FIGURE.parent.mkdir(parents=True, exist_ok=True)
    FIGURE.write_text(FIGURE_HEAD + "\n\n" + body.strip("\n") + "\n")


def wrap(key: str, body: str) -> str:
    """One block of results/grid_chart.md: marked if slides.md carries it inline,
    labelled with its figure file if the deck pulls it in as a figure instead."""
    if key in MARKS:
        a, b = MARKS[key]
        return f"{a}\n{body}\n{b}\n\n"
    return f"<!-- {key} -- the deck's copy is figures/{key}.md -->\n{body}\n\n"


def inject(text: str, key: str, body: str) -> str:
    a, b = MARKS[key]
    if a not in text or b not in text:
        raise SystemExit(f"markers for {key} not found in slides.md")
    i, j = text.index(a) + len(a), text.index(b)
    return text[:i] + "\n" + body.strip("\n") + "\n\n" + text[j:]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-slide", action="store_true",
                    help="write figures/results-alpha.md (the chart, its legend and "
                         "its styling script) and refresh the marked results-fit "
                         "block in slides.md")
    args = ap.parse_args()

    store = json.loads((ROOT / "results/grid.json").read_text())
    sweep = json.loads((ROOT / "results/alpha_sweep.json").read_text())
    v = fit_numbers(store)
    blocks = {"results-fit": fit_md(v), "results-alpha": alpha_chart_md(sweep)}
    OUT.write_text("".join(wrap(k, b) for k, b in blocks.items()))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  Chinchilla: {100*v['add'].rmse_log:.2f}% fit, "
          f"{100*v['add_test']:.2f}% at ~10x compute")
    print(f"  coupled:    {100*v['coupled'].rmse_log:.2f}% fit, "
          f"{100*v['coupled_test']:.2f}% at ~10x compute, q={v['coupled'].q:.2f}")

    if args.write_slide:
        write_figure(blocks["results-alpha"])
        text = SLIDES.read_text()
        for key in MARKS:
            text = inject(text, key, blocks[key])
        SLIDES.write_text(text)
        print(f"  wrote {FIGURE.relative_to(ROOT)} and the results-fit block "
              f"in {SLIDES.name}")


if __name__ == "__main__":
    main()
