"""The IsoFLOP slide: parabolas, their minima, and the two laws the minima define.

Draws the construction the compute-optimal numbers come from, as a two-panel SVG with
the deck's own reveal mechanism, so the audience sees it built in three beats:

    beat 0   six IsoFLOP profiles, a parabola in log N fitted to each, minimum marked
    beat 1   the line through the six minima -- the envelope -- with its exponent, which
             is -(alpha - 1): the model-size exponent read off the minima alone
    beat 2   the same minima against their own compute, N*(C), measured and fitted

Everything is fitted here and written out; the deck holds only numbers.  The SVG is
generated rather than hand-written because the point of the slide is that these are
*measurements*: no curve on it is drawn by hand.

    PYTHONPATH=src uv run python scripts/isoflop_slide.py                # fits + md
    PYTHONPATH=src uv run python scripts/isoflop_slide.py --write-slide  # inject

Writes results/isoflop_fits.json (every profile, every fit) and
results/isoflop_chart.md; --write-slide replaces the marked block in slides.md.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from assocmem.grid_fit import isoflop_detail  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
# The dedicated sweep (six widths per budget, centred on N*) when it exists, else the
# (N, D) grid's anti-diagonals, which carry only three or four points each.
SWEEP = ROOT / "results/isoflop_grid.json"
GRID = ROOT / "results/grid.json"
FITS = ROOT / "results/isoflop_fits.json"
OUT = ROOT / "results/isoflop_chart.md"
SLIDES = ROOT / "slides.md"
MARKS = {name: (f"<!-- BEGIN {name} (generated by scripts/isoflop_slide.py) -->",
                f"<!-- END {name} -->")
         for name in ("isoflop-figure", "isoflop-exponents")}

# Cheap to expensive, in the deck's single-hue ramp: the budgets are *ordered*.
RAMP = ("#86b6ef", "#6da7ec", "#5598e7", "#256abf", "#184f95", "#0d366b")
SURFACE = "#fcfcfb"

# Panel geometry, in viewBox units.  Two panels side by side, the second revealed on
# the second click -- the same shape as the "step function" slide earlier in the deck.
#
# Both reveal groups carry data-colloquium-fragment="1": colloquium's builder replaces
# every occurrence of that exact attribute with a *sequential* data-fragment-index, so
# the value is a marker, not the step number.  Anything else is left untouched and ends
# up permanently visible.
# The height matters: at full slide width a 1180x470 viewBox renders 613 px tall, which
# together with the title and the legend overflows the slide and pushes the figure off
# the bottom.  1180x400 leaves room.
W, H = 1180, 400
YT, YB = 18, 308  # plot box, top and bottom
AX0, AX1 = 152, 562  # left panel
BX0, BX1 = 764, 1152  # right panel


# ------------------------------------------------------------------ scales


class Log:
    """A log10 axis mapping data to viewBox units, plus its power-of-ten ticks."""

    def __init__(self, lo: float, hi: float, p0: float, p1: float):
        self.lo, self.hi, self.p0, self.p1 = lo, hi, p0, p1

    def __call__(self, v: float) -> float:
        t = (np.log10(v) - np.log10(self.lo)) / (np.log10(self.hi) - np.log10(self.lo))
        return self.p0 + t * (self.p1 - self.p0)

    def decades(self) -> list[int]:
        k0 = int(np.ceil(np.log10(self.lo) - 1e-9))
        k1 = int(np.floor(np.log10(self.hi) + 1e-9))
        return list(range(k0, k1 + 1))


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


# ------------------------------------------------------------------ svg pieces
#
# The target look is the deck's colloquium ```chart``` blocks on the following slides:
# one thin grey axis per side with the ticks and labels outside it, no grid in the plot
# area, a rotated axis title, small filled markers, and dashed grey for anything fitted.


def num(v: float) -> str:
    """Axis numbers the way the deck writes them: 10k, 100k, 1M, 1.5."""
    if v >= 1e6 and abs(v / 1e6 - round(v / 1e6)) < 1e-9:
        return f"{v / 1e6:g}M"
    if v >= 1e3:
        return f"{v / 1e3:g}k"
    return f"{v:g}"


def frame(sx: Log, sy: Log, x0: float, x1: float, xlab: str, ylab: str,
          x_ticks, y_ticks, x_fmt=num, y_fmt=num) -> list[str]:
    """The two axes, their ticks outside, and a rotated y title."""
    out = [f'<line class="pf-axis" x1="{x0}" y1="{YB}" x2="{x1}" y2="{YB}"/>',
           f'<line class="pf-axis" x1="{x0}" y1="{YB}" x2="{x0}" y2="{YT}"/>']
    for v in x_ticks:
        x = sx(v)
        out.append(f'<line class="pf-axis" x1="{x:.0f}" y1="{YB}" x2="{x:.0f}" '
                   f'y2="{YB + 8}"/>')
        out.append(f'<text class="pf-muted pf-small" x="{x:.0f}" y="{YB + 34}" '
                   f'text-anchor="middle">{x_fmt(v)}</text>')
    for v in y_ticks:
        y = sy(v)
        out.append(f'<line class="pf-axis" x1="{x0 - 8}" y1="{y:.0f}" x2="{x0}" '
                   f'y2="{y:.0f}"/>')
        out.append(f'<text class="pf-muted pf-small" x="{x0 - 14}" y="{y + 7:.0f}" '
                   f'text-anchor="end">{y_fmt(v)}</text>')
    cy = (YT + YB) / 2
    out.append(f'<text class="pf-muted pf-small" x="{(x0 + x1) / 2:.0f}" y="{YB + 72}" '
               f'text-anchor="middle">{xlab}</text>')
    out.append(f'<text class="pf-muted pf-small" transform="rotate(-90 {x0 - 74:.0f} '
               f'{cy:.0f})" x="{x0 - 74:.0f}" y="{cy:.0f}" text-anchor="middle">'
               f"{ylab}</text>")
    return out


def path(pts, sx: Log, sy: Log) -> str:
    d = " L ".join(f"{sx(x):.1f} {sy(y):.1f}" for x, y in pts)
    return f"M {d}"


def diamond(x: float, y: float, r: float = 6.0) -> str:
    return f"M {x:.1f} {y - r:.1f} L {x + r:.1f} {y:.1f} L {x:.1f} {y + r:.1f} " \
           f"L {x - r:.1f} {y:.1f} Z"


def sci_tex(c: float) -> str:
    """1.6e11 -> '1.6&#183;10<sup>11</sup>' for the HTML legend."""
    e = int(np.floor(np.log10(c)))
    m = c / 10.0**e
    head = "" if abs(m - 1) < 0.06 else f"{m:.1f}&#183;".replace(".0&#183;", "&#183;")
    return f"{head}10<sup>{e}</sup>"


def exponent_label(x: float, y: float, base: str, exp: str, anchor: str = "end") -> str:
    """`base` with a raised exponent, in the muted grey the fitted lines are drawn in."""
    return (f'<text class="pf-muted pf-small" x="{x:.0f}" y="{y:.0f}" '
            f'text-anchor="{anchor}">{base}<tspan dy="-9" font-size="0.72em">{exp}'
            f"</tspan></text>")


# ------------------------------------------------------------------ the figure


def figure_svg(det: dict) -> str:
    """Four beats: the measurements, the parabolas and their optima, the envelope, N*(C).

    Reveals are `<g class="fragment" data-colloquium-fragment="1">` groups; that literal
    attribute is a marker which colloquium replaces with a sequential index, so the order
    is document order and the value is never the step number.
    """
    profs = [p for p in det["profiles"] if not p["edge"]]
    fr, nc = det["laws"]["frontier"], det["laws"]["n_of_c"]
    if fr["exp"] is None or len(profs) < 2:
        raise SystemExit(f"only {len(profs)} profiles with an interior minimum: "
                         "run the whole sweep before drawing the figure")

    ns = [v for p in profs for v in p["n"]]
    ex = [v for p in profs for v in p["excess"]]
    ax = Log(1e4, 6e6, AX0, AX1)
    ay = Log(0.72, 1.72, YB, YT)
    assert min(ns) >= 1e4 and max(ns) <= 6e6, (min(ns), max(ns))
    assert min(ex) >= 0.72 and max(ex) <= 1.72, (min(ex), max(ex))

    s = [f'<svg class="plot-fig" viewBox="0 0 {W} {H}" role="img" aria-label="Left: '
         "loss against model size for six compute budgets, each a U-shaped IsoFLOP "
         "profile with a fitted parabola and its optimum marked; a dashed line through "
         "the optima has slope minus alpha minus one. Right: the compute-optimal model "
         'size against compute, measured and fitted.">',
         "<defs>",
         f'<clipPath id="if-a"><rect x="{AX0}" y="{YT - 10}" width="{AX1 - AX0}" '
         f'height="{YB - YT + 10}"/></clipPath>',
         f'<clipPath id="if-b"><rect x="{BX0}" y="{YT - 10}" width="{BX1 - BX0}" '
         f'height="{YB - YT + 10}"/></clipPath>',
         "</defs>",
         *frame(ax, ay, AX0, AX1, 'model size <tspan class="pf-var">N</tspan>', "loss",
                x_ticks=[10.0**k for k in ax.decades()], y_ticks=(0.8, 1.0, 1.2, 1.5))]

    # beat 0: the measurements alone
    for p, col in zip(profs, RAMP):
        for x, y in zip(p["n"], p["excess"]):
            s.append(f'<circle cx="{ax(x):.1f}" cy="{ay(y):.1f}" r="3.6" fill="{col}"/>')

    # beat 1: a parabola per budget, and where each one bottoms out
    s.append('<g class="fragment" data-colloquium-fragment="1">')
    s.append('<g clip-path="url(#if-a)">')
    for p, col in zip(profs, RAMP):
        s.append(f'<path d="{path(p["curve"], ax, ay)}" fill="none" stroke="{col}" '
                 f'stroke-width="2.4" stroke-linecap="round"/>')
    s.append("</g>")
    for p, col in zip(profs, RAMP):
        s.append(f'<path d="{diamond(ax(p["n_star"]), ay(p["excess_star"]))}" '
                 f'fill="{col}" stroke="{SURFACE}" stroke-width="1.6"/>')
    s.append("</g>")

    # beat 2: the envelope through the optima, labelled at the top in the same grey
    x0, x1 = 0.72 * min(p["n_star"] for p in profs), 1.5 * max(p["n_star"] for p in profs)
    line = [(x, fr["pref"] * x ** fr["exp"]) for x in np.geomspace(x0, x1, 3)]
    s += ['<g class="fragment" data-colloquium-fragment="1">',
          '<g clip-path="url(#if-a)">',
          f'<path class="pf-guide" d="{path(line, ax, ay)}"/>',
          "</g>",
          exponent_label(AX1 - 4, YT + 30,
                         '<tspan class="pf-var">L</tspan>* &#8733; '
                         '<tspan class="pf-var">C</tspan>',
                         f'&#8722;{abs(det["laws"]["l_of_c"]["exp"]):.3f}'),
          "</g>"]

    # beat 3: the same optima against their own compute, in units of 1e9
    bx = Log(5e9, 2.2e13, BX0, BX1)
    by = Log(3e4, 2.6e6, YB, YT)
    fit = [(c, nc["pref"] * c ** nc["exp"]) for c in np.geomspace(5e9, 2.2e13, 3)]
    c_lab = float(np.exp(0.72 * np.log(2.2e13) + 0.28 * np.log(5e9)))
    s += ['<g class="fragment" data-colloquium-fragment="1">',
          *frame(bx, by, BX0, BX1,
                 'compute <tspan class="pf-var">C</tspan> '
                 '(&#215;10<tspan dy="-9" font-size="0.72em">9</tspan>)',
                 'model size <tspan class="pf-var">N</tspan>*', x_ticks=[10.0**k for k in bx.decades()],
                 y_ticks=(1e5, 1e6), x_fmt=lambda v: num(v / 1e9)),
          '<g clip-path="url(#if-b)">',
          f'<path class="pf-guide" d="{path(fit, bx, by)}"/>',
          "</g>"]
    for p, col in zip(profs, RAMP):
        s.append(f'<path d="{diamond(bx(p["c"]), by(p["n_star"]))}" fill="{col}" '
                 f'stroke="{SURFACE}" stroke-width="1.6"/>')
    s += [exponent_label(bx(c_lab) - 6, by(nc["pref"] * c_lab ** nc["exp"]) - 16,
                         '<tspan class="pf-var">C</tspan>', f'{nc["exp"]:.3f}'),
          "</g>", "</svg>"]
    return "\n".join(s)

def legend_num(c: float) -> str:
    """A compute budget in units of 1e9, two significant figures: 10, 640, 2.6k."""
    v = c / 1e9
    v = round(v, -(int(np.floor(np.log10(v))) - 1))
    return num(v)


def legend_html(det: dict) -> str:
    profs = [p for p in det["profiles"] if not p["edge"]]
    spans = "\n".join(
        f'<span><svg width="30" height="10" viewBox="0 0 30 10" aria-hidden="true">'
        f'<line x1="1" y1="5" x2="29" y2="5" stroke="{c}" stroke-width="2.2"/>'
        f'<circle cx="15" cy="5" r="2.8" fill="{c}"/></svg>'
        f'{legend_num(p["c"])}</span>'
        for p, c in zip(profs, RAMP))
    return ('<div class="cap-legend">\n'
            '<span class="num"><em>C</em> (&#215;10<sup>9</sup>)</span>\n'
            f"{spans}\n</div>")


def comparison_line(det: dict) -> str:
    """One line closing the loop: both compute exponents, measured against predicted."""
    lc, nc = det["laws"]["l_of_c"], det["laws"]["n_of_c"]
    return (f'The loss falls as $C^{{{lc["exp"]:.4f}}}$ against a predicted '
            f'$C^{{{lc["theory"]:.4f}}}$, and the optimal model size grows as '
            f'$C^{{{nc["exp"]:.3f}}}$ against $C^{{{nc["theory"]:.3f}}}$.')


def body(det: dict, which: str = "isoflop-figure") -> str:
    if which == "isoflop-exponents":
        return comparison_line(det)
    # the legend beside the figure rather than above it: see .if-row in assets/slides.css
    return ('<div class="if-row">\n' + legend_html(det) + "\n" + figure_svg(det)
            + "\n</div>")


def write_slide(det: dict) -> list[str]:
    """Replace both marked blocks.  Returns the names that were not found."""
    text, missing = SLIDES.read_text(), []
    for name, (a, b) in MARKS.items():
        if a not in text or b not in text:
            missing.append(name)
            continue
        i, j = text.index(a) + len(a), text.index(b)
        text = text[:i] + "\n\n" + body(det, name) + "\n\n" + text[j:]
    SLIDES.write_text(text)
    return missing


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-slide", action="store_true")
    args = ap.parse_args()

    src = SWEEP if SWEEP.exists() else GRID
    det = isoflop_detail(json.loads(src.read_text()))
    det["source"] = str(src.relative_to(ROOT))
    FITS.write_text(json.dumps(det, indent=1))
    print(f"  profiles from {det['source']}")
    OUT.write_text("\n\n".join(body(det, n) for n in MARKS) + "\n")
    print(f"wrote {FITS.relative_to(ROOT)} and {OUT.relative_to(ROOT)}")
    print(f"  {det['n_fit']} profiles fitted, {det['n_edge']} dropped for an edge minimum")
    for p in det["profiles"]:
        flag = "  edge (dropped)" if p["edge"] else ""
        print(f"    C = {p['c']:.3e}  h {str(p['hs']):<26s} N* = {p['n_star']:9.0f}  "
              f"L*-Linf = {p['excess_star']:.4f}{flag}")
    for k, v in det["laws"].items():
        print(f"  {k:9s} exponent {v['exp']:+.4f}  (theory {v['theory']:+.4f}, "
              f"{100 * (v['exp'] / v['theory'] - 1):+.1f} %)  r2 {v['r2']:.5f}")
    if args.write_slide:
        missing = write_slide(det)
        print("wrote slides.md" + (f"  (MARKERS MISSING: {missing})" if missing else ""))


if __name__ == "__main__":
    main()
